import React, { useState, useEffect, useCallback } from 'react';
import { 
  Download,
  RefreshCw,
  TrendingUp,
  Package,
  Database,
  FileSpreadsheet,
  Eye,
  BarChart3,
  Save,
  CheckCircle,
  AlertCircle,
  Info
} from 'lucide-react';

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';

const TSPWAnalysis = ({ 
  uploadedFiles, 
  selectedSheets, 
  addMessage, 
  loading, 
  setLoading,
  storedFiles = [],
  setStoredFiles = () => {},
  onFileAdd = () => {}
}) => {
  const [activeSubTab, setActiveSubTab] = useState('mt');
  const [tsPwData, setTsPwData] = useState({
    mt_data: null,
    value_data: null,
    fiscal_year: '',
    columns: { mt: [], value: [] },
    shape: { mt: [0, 0], value: [0, 0] }
  });
  const [processing, setProcessing] = useState(false);
  const [fiscalInfo, setFiscalInfo] = useState({});
  const [autoExportEnabled, setAutoExportEnabled] = useState(true);
  const [hasCheckedSession, setHasCheckedSession] = useState(false);

  // Debug logging for props
  useEffect(() => {
    console.log('🔍 TSPWAnalysis Props Check:', {
      storedFiles: storedFiles.length,
      setStoredFiles: typeof setStoredFiles,
      onFileAdd: typeof onFileAdd,
      autoExportEnabled
    });
  }, [storedFiles, setStoredFiles, onFileAdd, autoExportEnabled]);

  const canProcess = useCallback(() => {
    return uploadedFiles.budget && selectedSheets.budget;
  }, [uploadedFiles.budget, selectedSheets.budget]);

  // UPDATED: Store file in session function - Latest only storage pattern
  const storeFileInSession = useCallback(async (fileBlob, fileName, analysisType, fileDescription) => {
    try {
      const timestamp = new Date().toISOString();
      const fileUrl = URL.createObjectURL(fileBlob);
      
      const storedFileData = {
        id: `tspw_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        name: fileName,
        blob: fileBlob,
        size: fileBlob.size,
        url: fileUrl,
        createdAt: timestamp,
        fiscalYear: fiscalInfo.current_year || tsPwData.fiscal_year || 'N/A',
        type: `tspw-${analysisType}`,
        source: 'TS-PW Analysis (NORTH)',
        description: fileDescription,
        mtRecords: analysisType === 'mt' || analysisType.includes('combined') ? 
          (tsPwData.shape?.mt?.[0] || 0) : 0,
        valueRecords: analysisType === 'value' || analysisType.includes('combined') ? 
          (tsPwData.shape?.value?.[0] || 0) : 0,
        sheets: analysisType.includes('combined') ? 
          ['Combined TS-PW Analysis'] :
          [`TSPW ${analysisType.toUpperCase()} Analysis`],
        analysisType: analysisType,
        metadata: {
          singleSheet: analysisType.includes('single-sheet'),
          bothTables: analysisType.includes('combined'),
          columnOrdered: true,
          fiscalYear: fiscalInfo.current_year || tsPwData.fiscal_year,
          analysisType: 'tspw',
          autoGenerated: analysisType.includes('auto'),
          integration: {
            combined_data_ready: true,
            sync_status: 'ready'
          }
        },
        tags: ['tspw', 'north', 'analysis', analysisType.includes('combined') ? 'combined' : 'individual']
      };

      console.log('🔄 Storing TS-PW file (replacing previous):', {
        fileName,
        analysisType,
        fileSize: fileBlob.size
      });

      // Remove any existing TS-PW files to keep only the latest
      if (typeof setStoredFiles === 'function') {
        setStoredFiles(prev => {
          // Remove old TS-PW files and clean up their URLs
          const oldTsPwFiles = prev.filter(f => f.type && f.type.includes('tspw'));
          oldTsPwFiles.forEach(file => {
            if (file.url) {
              URL.revokeObjectURL(file.url);
            }
          });
          
          // Keep only non-TS-PW files and add the new one
          const otherFiles = prev.filter(f => !f.type || !f.type.includes('tspw'));
          return [storedFileData, ...otherFiles];
        });
        
        console.log('✅ TS-PW file replaced (keeping only latest)');
        addMessage(`💾 ${fileName} stored (previous TS-PW file replaced)`, 'success');
        return storedFileData;
      }
      
      // Fallback: try onFileAdd if setStoredFiles not available
      if (typeof onFileAdd === 'function') {
        onFileAdd(storedFileData);
        console.log('✅ TS-PW file added via onFileAdd callback');
        addMessage(`💾 ${fileName} stored in Combined Excel Manager`, 'success');
        return storedFileData;
      }

      addMessage('⚠️ File generated but could not be stored', 'warning');
      return null;
    } catch (error) {
      console.error('❌ Error storing TS-PW file:', error);
      addMessage(`❌ Error storing file: ${error.message}`, 'error');
      return null;
    }
  }, [fiscalInfo, tsPwData, addMessage, onFileAdd, setStoredFiles]);

  // Auto-generate and store combined Excel file
  const autoGenerateTsPwReport = useCallback(async () => {
    if (!autoExportEnabled) {
      console.log('🚫 Auto-export disabled, skipping auto-generation');
      return;
    }
    
    const hasMtData = tsPwData.mt_data && tsPwData.mt_data.length > 0;
    const hasValueData = tsPwData.value_data && tsPwData.value_data.length > 0;
    
    if (!hasMtData && !hasValueData) {
      console.log('🚫 No data available for auto-generation');
      return;
    }

    console.log('🤖 Auto-generating TS-PW report...');

    try {
      const timestamp = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
      const fileName = `tspw_auto_combined_${tsPwData.fiscal_year || 'report'}_${timestamp}.xlsx`;

      const response = await fetch(`${API_BASE_URL}/ts-pw/export-combined-ts-pw-excel`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mt_data: tsPwData.mt_data || [],
          value_data: tsPwData.value_data || [],
          mt_columns: tsPwData.columns.mt || [],
          value_columns: tsPwData.columns.value || [],
          fiscal_year: tsPwData.fiscal_year,
          auto_generated: true
        })
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const result = await response.json();
      
      if (result.success) {
        const byteCharacters = atob(result.data);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const blob = new Blob([byteArray], { 
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
        });

        const fileDescription = `Auto-generated combined TS-PW analysis with MT (${hasMtData ? tsPwData.mt_data.length : 0} records) and Value (${hasValueData ? tsPwData.value_data.length : 0} records) for fiscal year ${tsPwData.fiscal_year}`;
        await storeFileInSession(blob, fileName, 'combined-auto', fileDescription);
        
        addMessage(`🤖 Auto-generated: ${fileName}`, 'success');
        return result;
      }
    } catch (error) {
      console.error('❌ Auto-generation error:', error);
      addMessage(`❌ Auto-generation error: ${error.message}`, 'error');
    }
  }, [autoExportEnabled, tsPwData, storeFileInSession, addMessage]);

  // Auto-generate when both tables are available
  useEffect(() => {
    if (autoExportEnabled && tsPwData.mt_data && tsPwData.value_data) {
      const timer = setTimeout(() => {
        autoGenerateTsPwReport();
      }, 2000); // 2 second delay after processing completes
      
      return () => clearTimeout(timer);
    }
  }, [tsPwData.mt_data, tsPwData.value_data, autoExportEnabled, autoGenerateTsPwReport]);

  const processTsPwData = useCallback(async () => {
    if (!canProcess()) {
      addMessage('Budget file and sheet selection are required for TS-PW analysis', 'error');
      return;
    }

    setProcessing(true);
    setLoading(true);
    
    try {
      const requestData = {
        budget_filepath: uploadedFiles.budget.filepath,
        budget_sheet: selectedSheets.budget,
        sales_filepath: uploadedFiles.sales?.filepath || null,
        sales_sheets: selectedSheets.sales ? [selectedSheets.sales] : [],
        last_year_filepath: uploadedFiles.totalSales?.filepath || null,
        last_year_sheet: selectedSheets.totalSales || null
      };

      addMessage('🔄 Processing TS-PW analysis...', 'info');

      const response = await fetch(`${API_BASE_URL}/ts-pw/process-ts-pw`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(requestData)
      });

      const result = await response.json();

      if (result.success) {
        setTsPwData(result.data);
        
        // Extract fiscal info
        const resultFiscalInfo = {
          current_year: result.data.fiscal_year || '25-26'
        };
        setFiscalInfo(resultFiscalInfo);
        
        // Auto-switch to available tab
        if (result.data.value_data && result.data.value_data.length > 0) {
          setActiveSubTab('value');
        } else if (result.data.mt_data && result.data.mt_data.length > 0) {
          setActiveSubTab('mt');
        }
        
        const mtRows = result.data.shape.mt[0];
        const valueRows = result.data.shape.value[0];
        
        if (mtRows > 0 && valueRows > 0) {
          addMessage(`✅ TS-PW analysis completed successfully - MT: ${mtRows} rows, Value: ${valueRows} rows`, 'success');
        } else if (mtRows > 0) {
          addMessage(`✅ TS-PW analysis completed - MT: ${mtRows} rows (Value data not available)`, 'success');
        } else if (valueRows > 0) {
          addMessage(`✅ TS-PW analysis completed - Value: ${valueRows} rows (MT data not available)`, 'success');
        } else {
          addMessage('⚠️ TS-PW analysis completed but no data was generated. Please check your input files.', 'warning');
        }
      } else {
        addMessage(result.error || 'TS-PW processing failed', 'error');
      }
    } catch (error) {
      addMessage(`❌ TS-PW processing error: ${error.message}`, 'error');
    } finally {
      setLoading(false);
      setProcessing(false);
    }
  }, [canProcess, uploadedFiles, selectedSheets, addMessage, setLoading]);

  // Auto-process on data availability
  useEffect(() => {
    const timer = setTimeout(() => {
      if (canProcess() && !processing && !tsPwData.mt_data && !tsPwData.value_data) {
        console.log('🔄 Auto-processing TS-PW analysis...');
        processTsPwData();
      }
    }, 1000);

    return () => clearTimeout(timer);
  }, [uploadedFiles, selectedSheets, canProcess, processTsPwData, processing, tsPwData]);

  // Export function (download only)
  const exportTsPwReport = async () => {
    const hasMtData = tsPwData.mt_data && tsPwData.mt_data.length > 0;
    const hasValueData = tsPwData.value_data && tsPwData.value_data.length > 0;
    
    if (!hasMtData && !hasValueData) {
      addMessage('No TS-PW data available to export. Please ensure MT or Value analysis completed successfully.', 'error');
      return;
    }

    console.log('📤 Exporting TS-PW tables for download');
    setLoading(true);
    
    try {
      const timestamp = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
      const fileName = `tspw_combined_${fiscalInfo.current_year || tsPwData.fiscal_year || 'report'}_${timestamp}.xlsx`;

      const response = await fetch(`${API_BASE_URL}/ts-pw/export-combined-ts-pw-excel`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          mt_data: tsPwData.mt_data || [],
          value_data: tsPwData.value_data || [],
          mt_columns: tsPwData.columns.mt || [],
          value_columns: tsPwData.columns.value || [],
          fiscal_year: fiscalInfo.current_year || tsPwData.fiscal_year || ''
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }

      const result = await response.json();
      
      if (result.success) {
        const byteCharacters = atob(result.data);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const blob = new Blob([byteArray], { 
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
        });

        // Download the file
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        
        addMessage(`📁 TS-PW analysis exported successfully`, 'success');
      } else {
        addMessage(result.error || 'Export failed', 'error');
      }
    } catch (error) {
      addMessage(`❌ Export error: ${error.message}`, 'error');
    } finally {
      setLoading(false);
    }
  };

  const formatNumber = (value) => {
    if (typeof value === 'number') {
      return value.toLocaleString('en-IN', { 
        minimumFractionDigits: 2, 
        maximumFractionDigits: 2 
      });
    }
    return value;
  };

  // Get TS-PW specific files from global storage
  const getTsPwFiles = () => {
    return storedFiles.filter(f => f.type && f.type.includes('tspw'));
  };

  const DataTable = ({ data, title, analysisType }) => {
    if (!data || !data.length) return null;

    const columns = tsPwData.columns[analysisType] || [];

    return (
      <div className="data-preview">
        <div className="preview-header">
          <h4>{title}</h4>
        </div>
        
        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                {columns.map((col, index) => (
                  <th key={index} className={index === 0 ? 'sticky-col product-header' : 'data-header'}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.slice(0, 100).map((row, rowIndex) => {
                const isTotal = row[columns[0]]?.toString().toUpperCase().includes('TOTAL');
                return (
                  <tr key={rowIndex} className={isTotal ? 'total-row' : ''}>
                    {columns.map((col, colIndex) => {
                      const value = row[col];
                      const isNumeric = typeof value === 'number' && !isNaN(value);
                      const formattedValue = isNumeric ? formatNumber(value) : (value || '');
                      
                      return (
                        <td 
                          key={colIndex} 
                          className={`${colIndex === 0 ? 'sticky-col product-cell' : 'data-cell'} ${isNumeric ? 'numeric' : ''}`}
                        >
                          {formattedValue}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        
        {data.length > 100 && (
          <div className="table-note">
            Showing first 100 rows of {data.length} total rows
          </div>
        )}
      </div>
    );
  };

  // Auto-export toggle component
  const AutoExportToggle = () => (
    <div className="auto-export-control">
      <label className="toggle-label">
        <input
          type="checkbox"
          checked={autoExportEnabled}
          onChange={(e) => setAutoExportEnabled(e.target.checked)}
          className="toggle-input"
        />
        <span className="toggle-switch"></span>
        Auto-generate and store combined Excel file
      </label>
      <small className="toggle-help">
        When enabled, the latest combined TS-PW Excel file will be automatically generated and stored
      </small>
    </div>
  );

  const TablesPreviewTab = () => {
    const tsPwFiles = getTsPwFiles();
    
    return (
      <div className="tables-preview-section">
        <div className="preview-intro">
          <h3>📊 TS-PW Analysis Tables (NORTH)</h3>
          <p>View both TS-PW SALES in Tonnage and SALES in Value tables generated from your data processing.</p>
          
          {/* Auto-export control */}
          <AutoExportToggle />
        </div>

        <div className="table-section">
          <div className="table-section-header">
            <h4>🏭 TS-PW SALES in Tonnage Table</h4>
            <div className="table-status">
              {tsPwData.mt_data ? (
                <span className="status-badge available">✅ Available ({tsPwData.shape.mt[0]} records)</span>
              ) : (
                <span className="status-badge unavailable">❌ Not Available</span>
              )}
            </div>
          </div>

          {tsPwData.mt_data ? (
            <DataTable
              data={tsPwData.mt_data}
              title={`TS-PW Monthly Budget and Actual Tonnage (NORTH) [${fiscalInfo.current_year || tsPwData.fiscal_year || '25-26'}]`}
              analysisType="mt"
            />
          ) : (
            <div className="table-empty-state">
              <Package size={48} />
              <h4>No TS-PW Tonnage Data Available</h4>
              <p>
                {!canProcess() ? 
                  "Upload Budget file to start analysis" :
                  "Click 'Refresh Analysis' to generate MT data"
                }
              </p>
            </div>
          )}
        </div>

        <div className="table-separator"></div>

        <div className="table-section">
          <div className="table-section-header">
            <h4>💰 TS-PW SALES in Value Table</h4>
            <div className="table-status">
              {tsPwData.value_data ? (
                <span className="status-badge available">✅ Available ({tsPwData.shape.value[0]} records)</span>
              ) : (
                <span className="status-badge unavailable">❌ Not Available</span>
              )}
            </div>
          </div>

          {tsPwData.value_data ? (
            <DataTable
              data={tsPwData.value_data}
              title={`TS-PW Monthly Budget and Actual Value (NORTH) [${fiscalInfo.current_year || tsPwData.fiscal_year || '25-26'}]`}
              analysisType="value"
            />
          ) : (
            <div className="table-empty-state">
              <TrendingUp size={48} />
              <h4>No TS-PW Value Data Available</h4>
              <p>
                {!canProcess() ? 
                  "Upload Budget file to start analysis" :
                  "Click 'Refresh Analysis' to generate Value data"
                }
              </p>
            </div>
          )}
        </div>

        <div className="tables-summary">
          <h4>📊 TS-PW Analysis Export</h4>
          {(tsPwData.mt_data || tsPwData.value_data) && (
            <div className="export-merged-section">
              <div className="export-actions">
                <button
                  onClick={exportTsPwReport}
                  className="btn btn-primary btn-large"
                  disabled={loading}
                  title="Download TS-PW report"
                >
                  <Download size={16} />
                  {loading ? 'Processing...' : 'Download TS-PW Report'}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="tspw-analysis-section">
      <div className="section-header">
        <h2>📊 TS-PW Analysis (NORTH)</h2>
        <div className="header-actions">
          <button
            onClick={processTsPwData}
            className="btn btn-primary"
            disabled={!canProcess() || loading || processing}
          >
            {processing ? <RefreshCw size={16} /> : <BarChart3 size={16} />}
            {processing ? 'Processing...' : 'Refresh Analysis'}
          </button>

          {/* Combined Data Integration Status */}
          {getTsPwFiles().length > 0 && (
            <div className="integration-status-badge">
              <Package size={14} />
              <span>Latest file stored</span>
              <span className="latest-indicator">Latest Only</span>
            </div>
          )}
        </div>
      </div>

      <div className="stats-overview">
        <div className="stat-card">
          <Package className="stat-icon" />
          <div>
            <span className="stat-number">{tsPwData.shape.mt[0]}</span>
            <span className="stat-label">TS-PW Tonnage Records</span>
          </div>
        </div>
        <div className="stat-card">
          <TrendingUp className="stat-icon" />
          <div>
            <span className="stat-number">{tsPwData.shape.value[0]}</span>
            <span className="stat-label">TS-PW Value Records</span>
          </div>
        </div>
        <div className="stat-card">
          <Database className="stat-icon" />
          <div>
            <span className="stat-number">
              {getTsPwFiles().length > 0 ? '1' : '0'}
            </span>
            <span className="stat-label">Latest File</span>
          </div>
        </div>
      </div>

      <nav className="sub-tab-navigation">
        <button
          className={`sub-tab ${activeSubTab === 'mt' ? 'active' : ''}`}
          onClick={() => setActiveSubTab('mt')}
          disabled={!tsPwData.mt_data && !processing}
        >
          <Package size={16} />
          SALES in Tonnage
          {tsPwData.mt_data && <span className="data-indicator">●</span>}
        </button>
        <button
          className={`sub-tab ${activeSubTab === 'value' ? 'active' : ''}`}
          onClick={() => setActiveSubTab('value')}
          disabled={!tsPwData.value_data && !processing}
        >
          <TrendingUp size={16} />
          SALES in Value
          {tsPwData.value_data && <span className="data-indicator">●</span>}
        </button>
        <button
          className={`sub-tab ${activeSubTab === 'tables' ? 'active' : ''}`}
          onClick={() => setActiveSubTab('tables')}
        >
          <Eye size={16} />
          Tables Preview
          {getTsPwFiles().length > 0 && <span className="data-indicator">●</span>}
        </button>
      </nav>

      <div className="sub-tab-content">
        {activeSubTab === 'mt' && (
          <div className="mt-analysis">
            {tsPwData.mt_data ? (
              <DataTable
                data={tsPwData.mt_data}
                title={`TS-PW Monthly Budget and Actual Tonnage (NORTH) [${fiscalInfo.current_year || tsPwData.fiscal_year || '25-26'}]`}
                analysisType="mt"
              />
            ) : (
              <div className="empty-state">
                <Package size={48} />
                <h3>No MT analysis data</h3>
                <p>
                  {!canProcess() ? 
                    "Upload Budget file to start analysis" :
                    "Click 'Refresh Analysis' to generate MT data"
                  }
                </p>
                {canProcess() && (
                  <button
                    onClick={processTsPwData}
                    className="btn btn-primary"
                    disabled={loading || processing}
                  >
                    <Package size={16} />
                    Generate MT Analysis
                  </button>
                )}
              </div>
            )}
          </div>
        )}

        {activeSubTab === 'value' && (
          <div className="value-analysis">
            {tsPwData.value_data ? (
              <DataTable
                data={tsPwData.value_data}
                title={`TS-PW Monthly Budget and Actual Value (NORTH) [${fiscalInfo.current_year || tsPwData.fiscal_year || '25-26'}]`}
                analysisType="value"
              />
            ) : (
              <div className="empty-state">
                <TrendingUp size={48} />
                <h3>No Value analysis data</h3>
                <p>
                  {!canProcess() ? 
                    "Upload Budget file to start analysis" :
                    "Click 'Refresh Analysis' to generate Value data"
                  }
                </p>
                {canProcess() && (
                  <button
                    onClick={processTsPwData}
                    className="btn btn-primary"
                    disabled={loading || processing}
                  >
                    <TrendingUp size={16} />
                    Generate Value Analysis
                  </button>
                )}
              </div>
            )}
          </div>
        )}

        {activeSubTab === 'tables' && <TablesPreviewTab />}
      </div>

      {processing && (
        <div className="processing-indicator">
          <RefreshCw size={24} />
          <span>Processing TS-PW analysis...</span>
        </div>
      )}

      <style jsx>{`
        .tspw-analysis-section {
          padding: 20px;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
          background-color: #f8f9fa;
          min-height: 100vh;
        }

        .section-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
          background: white;
          padding: 20px;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .section-header h2 {
          margin: 0;
          color: #333;
          font-size: 24px;
          font-weight: 600;
        }

        .header-actions {
          display: flex;
          gap: 10px;
          align-items: center;
        }

        .integration-status-badge {
          display: flex;
          align-items: center;
          gap: 6px;
          background: linear-gradient(135deg, #28a745, #20c997);
          color: white;
          padding: 8px 12px;
          border-radius: 16px;
          font-size: 12px;
          font-weight: 500;
          animation: pulse 2s infinite;
          position: relative;
        }

        .latest-indicator {
          background: rgba(255, 255, 255, 0.2);
          padding: 2px 6px;
          border-radius: 8px;
          font-size: 10px;
          margin-left: 4px;
        }

        @keyframes pulse {
          0% { transform: scale(1); }
          50% { transform: scale(1.05); }
          100% { transform: scale(1); }
        }

        .stats-overview {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 15px;
          margin-bottom: 20px;
        }

        .stat-card {
          background: white;
          padding: 20px;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          display: flex;
          align-items: center;
          gap: 15px;
          transition: transform 0.2s, box-shadow 0.2s;
        }

        .stat-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 8px rgba(0,0,0,0.15);
        }

        .stat-icon {
          width: 40px;
          height: 40px;
          color: #667eea;
          flex-shrink: 0;
        }

        .stat-number {
          display: block;
          font-size: 24px;
          font-weight: bold;
          color: #333;
          line-height: 1.2;
        }

        .stat-label {
          display: block;
          font-size: 12px;
          color: #666;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .sub-tab-navigation {
          display: flex;
          gap: 2px;
          margin-bottom: 20px;
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          overflow: hidden;
        }

        .sub-tab {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 16px 24px;
          background: none;
          border: none;
          border-bottom: 3px solid transparent;
          cursor: pointer;
          font-size: 14px;
          font-weight: 500;
          color: #6c757d;
          transition: all 0.2s ease;
          position: relative;
          flex: 1;
          justify-content: center;
        }

        .sub-tab:hover:not(:disabled) {
          color: #495057;
          background: rgba(102, 126, 234, 0.1);
        }

        .sub-tab.active {
          color: #667eea;
          border-bottom-color: #667eea;
          font-weight: 600;
          background: white;
        }

        .sub-tab:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .data-indicator {
          color: #28a745;
          font-size: 18px;
          line-height: 1;
        }

        .sub-tab-content {
          min-height: 400px;
        }

        .tables-preview-section {
          padding: 0;
        }

        .preview-intro {
          text-align: center;
          margin-bottom: 30px;
          padding: 24px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          border-radius: 8px;
        }

        .preview-intro h3 {
          margin: 0 0 10px 0;
          font-size: 24px;
          font-weight: 600;
        }

        .preview-intro p {
          margin: 0 0 20px 0;
          font-size: 16px;
          opacity: 0.9;
        }

        .auto-export-control {
          margin: 24px 0;
          padding: 20px;
          background: rgba(255, 255, 255, 0.1);
          border-radius: 8px;
          border: 1px solid rgba(255, 255, 255, 0.2);
        }

        .toggle-label {
          display: flex;
          align-items: center;
          gap: 12px;
          cursor: pointer;
          font-size: 14px;
          font-weight: 500;
          color: white;
        }

        .toggle-input {
          display: none;
        }

        .toggle-switch {
          position: relative;
          width: 44px;
          height: 24px;
          background: rgba(255, 255, 255, 0.3);
          border-radius: 12px;
          transition: background 0.3s ease;
        }

        .toggle-switch::before {
          content: '';
          position: absolute;
          top: 2px;
          left: 2px;
          width: 20px;
          height: 20px;
          background: white;
          border-radius: 50%;
          transition: transform 0.3s ease;
        }

        .toggle-input:checked + .toggle-switch {
          background: rgba(255, 255, 255, 0.6);
        }

        .toggle-input:checked + .toggle-switch::before {
          transform: translateX(20px);
        }

        .toggle-help {
          display: block;
          margin-top: 8px;
          color: rgba(255, 255, 255, 0.8);
          font-size: 12px;
          font-style: italic;
          line-height: 1.4;
        }

        .table-section {
          margin-bottom: 32px;
          border: 1px solid #e0e0e0;
          border-radius: 12px;
          overflow: hidden;
          background: white;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .table-section-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 20px 24px;
          background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
          border-bottom: 1px solid #e0e0e0;
        }

        .table-section-header h4 {
          margin: 0;
          color: #333;
          font-size: 18px;
          font-weight: 600;
        }

        .table-status {
          display: flex;
          align-items: center;
        }

        .status-badge {
          padding: 6px 12px;
          border-radius: 16px;
          font-size: 12px;
          font-weight: 600;
          border: 1px solid;
        }

        .status-badge.available {
          background: #d4edda;
          color: #155724;
          border-color: #c3e6cb;
        }

        .status-badge.unavailable {
          background: #f8d7da;
          color: #721c24;
          border-color: #f5c6cb;
        }

        .table-empty-state {
          text-align: center;
          padding: 80px 24px;
          color: #666;
        }

        .table-empty-state h4 {
          margin: 24px 0 16px;
          color: #333;
          font-size: 20px;
          font-weight: 600;
        }

        .table-empty-state p {
          color: #666;
          max-width: 500px;
          margin: 0 auto;
          line-height: 1.6;
          font-size: 16px;
        }

        .table-separator {
          height: 24px;
        }

        .tables-summary {
          background: white;
          border: 1px solid #e0e0e0;
          border-radius: 12px;
          padding: 24px;
          margin-top: 32px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .tables-summary h4 {
          margin: 0 0 20px 0;
          color: #333;
          font-size: 20px;
          font-weight: 600;
        }

        .export-merged-section {
          margin-top: 25px;
          padding: 20px;
          background: white;
          border: 2px dashed #667eea;
          border-radius: 8px;
          text-align: center;
        }

        .export-actions {
          display: flex;
          gap: 12px;
          justify-content: center;
          flex-wrap: wrap;
        }

        .empty-state {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 60px 20px;
          text-align: center;
          color: #6c757d;
        }

        .empty-state svg {
          color: #dee2e6;
          margin-bottom: 20px;
        }

        .empty-state h3 {
          margin: 0 0 10px 0;
          font-size: 18px;
          color: #495057;
        }

        .empty-state p {
          margin: 0 0 20px 0;
          font-size: 14px;
          max-width: 400px;
        }

        .data-preview {
          background: white;
          border-radius: 0;
          overflow: hidden;
        }

        .preview-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 15px 20px;
          background: #f8f9fa;
          border-bottom: 1px solid #dee2e6;
        }

        .preview-header h4 {
          margin: 0;
          font-size: 16px;
          font-weight: 600;
        }

        .table-container {
          overflow-x: auto;
          max-height: 600px;
          overflow-y: auto;
        }

        .data-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 13px;
        }

        .data-table th {
          background: #f8fafc;
          color: #374151;
          padding: 10px 8px;
          text-align: left;
          font-weight: 600;
          position: sticky;
          top: 0;
          z-index: 10;
          border-bottom: 2px solid #e2e8f0;
          border-right: 1px solid #e2e8f0;
        }

        .data-table th.product-header {
          background: #667eea !important;
          color: white !important;
          min-width: 250px;
          position: sticky;
          left: 0;
          z-index: 11;
        }

        .data-table th.data-header {
          text-align: center !important;
          min-width: 100px;
        }

        .data-table td {
          padding: 8px;
          border-bottom: 1px solid #f1f5f9;
          border-right: 1px solid #f1f5f9;
          white-space: nowrap;
        }

        .data-table td.product-cell {
          font-weight: 500;
          color: #1e293b;
          background: #f8fafc;
          position: sticky;
          left: 0;
          z-index: 5;
          border-right: 2px solid #667eea;
          min-width: 250px;
          word-wrap: break-word;
        }

        .data-table td.data-cell {
          font-family: 'Courier New', monospace;
          font-size: 13px;
          text-align: right;
        }

        .data-table td.numeric {
          text-align: right;
        }

        .data-table tr.total-row {
          background: #e2efda !important;
          font-weight: 600;
        }

        .data-table tr.total-row td.product-cell {
          background: #c3e6cb !important;
          color: #155724 !important;
          font-weight: 700;
        }

        .data-table tr:hover {
          background: #f8f9fa;
        }

        .data-table tr:hover td.product-cell {
          background: #e9ecef;
        }

        .data-table tr.total-row:hover {
          background: #d5e8d4 !important;
        }

        .data-table tr.total-row:hover td.product-cell {
          background: #b3d7b8 !important;
        }

        .table-note {
          padding: 10px 20px;
          background: #f8fafc;
          border-top: 1px solid #dee2e6;
          font-size: 12px;
          color: #6c757d;
          text-align: center;
        }

        .processing-indicator {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          padding: 40px;
          color: #666;
          background: white;
          border-radius: 8px;
          margin: 20px 0;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .btn {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 10px 16px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s ease;
          text-decoration: none;
          font-family: inherit;
        }

        .btn:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none !important;
        }

        .btn-primary {
          background: #667eea;
          color: white;
          box-shadow: 0 2px 4px rgba(102, 126, 234, 0.3);
        }

        .btn-primary:hover:not(:disabled) {
          background: #5a67d8;
          transform: translateY(-1px);
          box-shadow: 0 4px 8px rgba(102, 126, 234, 0.4);
        }

        .btn-secondary {
          background: #6c757d;
          color: white;
          box-shadow: 0 2px 4px rgba(108, 117, 125, 0.3);
        }

        .btn-secondary:hover:not(:disabled) {
          background: #545b62;
          transform: translateY(-1px);
          box-shadow: 0 4px 8px rgba(108, 117, 125, 0.4);
        }

        .btn-large {
          padding: 14px 28px;
          font-size: 16px;
          font-weight: 600;
        }

        /* Responsive Design */
        @media (max-width: 1024px) {
          .tspw-analysis-section {
            padding: 16px;
          }

          .export-actions {
            flex-direction: column;
            align-items: stretch;
          }
        }

        @media (max-width: 768px) {
          .tspw-analysis-section {
            padding: 12px;
          }

          .section-header {
            flex-direction: column;
            gap: 16px;
            align-items: stretch;
            text-align: center;
          }

          .stats-overview {
            grid-template-columns: 1fr;
          }

          .sub-tab-navigation {
            flex-direction: column;
          }

          .sub-tab {
            justify-content: flex-start;
            padding: 14px 20px;
          }

          .table-section-header {
            flex-direction: column;
            gap: 12px;
            align-items: stretch;
            text-align: center;
          }

          .export-actions {
            flex-direction: column;
            align-items: stretch;
          }

          .data-table {
            font-size: 12px;
          }

          .data-table th,
          .data-table td {
            padding: 8px 10px;
          }

          .data-table th.product-header,
          .data-table td.product-cell {
            min-width: 200px;
          }
        }

        @media (max-width: 480px) {
          .tspw-analysis-section {
            padding: 8px;
          }

          .section-header {
            padding: 16px;
          }

          .section-header h2 {
            font-size: 20px;
          }

          .stat-card {
            padding: 16px;
          }

          .stat-icon {
            width: 32px;
            height: 32px;
          }

          .stat-number {
            font-size: 20px;
          }

          .sub-tab {
            padding: 12px 16px;
            font-size: 13px;
          }

          .preview-intro {
            padding: 20px;
          }

          .preview-intro h3 {
            font-size: 20px;
          }

          .tables-summary {
            padding: 16px;
          }

          .data-table {
            font-size: 11px;
          }

          .data-table th,
          .data-table td {
            padding: 6px 8px;
          }

          .btn {
            padding: 8px 12px;
            font-size: 13px;
          }
        }
      `}</style>
    </div>
  );
};

export default TSPWAnalysis;